# [Chevereto](https://github.com/Chevereto/Chevereto-Free) is an image hosting
# software that allows you to create a beautiful and full-featured image hosting
# website on your own server. It's your hosting and your rules, so say goodbye
# to closures and restrictions.

---
version: "2"
services:
  chevereto:
    image: ghcr.io/linuxserver/chevereto
    container_name: chevereto
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
      - /path/to/data:/data
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - chevereto-db

  chevereto-db:
    image: ghcr.io/linuxserver/mariadb
    container_name: chevereto-db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=<yourrootpass>
      - MYSQL_DATABASE=chevereto
      - MYSQL_USER=chevereto
      - MYSQL_PASSWORD=<yourdbpass>
    volumes:
      - /path/to/config:/config
    restart: unless-stopped

