# [Duckdns](https://duckdns.org/) is a free service which will point a DNS (sub
# domains of duckdns.org) to an IP of your choice. The service is completely
# free, and doesn't require reactivation or forum posts to maintain its
# existence.

---
version: "2.1"
services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      # for UserID
      - PUID=${PUID:-1024} # optional
      # for GroupID
      - PGID=${PGID:-100} # optional
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=Etc/UTC # optional
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
      # multiple subdomains allowed, comma separated, no spaces
      - SUBDOMAINS=subdomain1,subdomain2
      # DuckDNS token
      - TOKEN=token
      # Set to `true` to log to file (also need to map /config).
      - LOG_FILE=false # optional
    volumes:
      # Used in conjunction with logging to file.
      - ${BASEDIR:-/volume1/docker}/duckdns/config:/config # optional
    restart: unless-stopped
