# [Duplicati](https://www.duplicati.com/) works with standard protocols like
# FTP, SSH, WebDAV as well as popular services like Microsoft OneDrive, Amazon
# Cloud Drive & S3, Google Drive, box.com, Mega, hubiC and many others.

---
version: "2.1"
services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=Etc/UTC
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
      # Optionally specify any [CLI variables](https://duplicati.readthedocs.io/en/latest/07-other-command-line-utilities/) you want to launch the app with
      - CLI_ARGS= # optional
    volumes:
      # Contains all relevant configuration files.
      - ${BASEDIR:-/volume1/docker}/duplicati/config:/config
      # Path to store local backups.
      - ${BASEDIR:-/volume1/docker}/duplicati/backups:/backups
      # Path to source for files to backup.
      - ${BASEDIR:-/volume1/docker}/duplicati/source:/source
    ports:
      # http gui
      - 8200:8200
    restart: unless-stopped
