# [Audacity]({{ project_url }}) is an easy-to-use, multi-track audio editor and
# recorder. Developed by a group of volunteers as open source.

---
version: "2.1"
services:
  audacity:
    image: ghcr.io/linuxserver/audacity
    container_name: audacity
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Users home directory in the container, stores program settings and images
      - ${BASEDIR:-/volume1/docker}/audacity/config:/config
    ports:
      # Audacity desktop gui.
      - 3000:3000
    restart: unless-stopped
