# Pydio (formerly AjaXplorer) is a mature open source software solution for file
# sharing and synchronization. With intuitive user interfaces (web / mobile /
# desktop), Pydio provides enterprise-grade features to gain back control and
# privacy of your data: user directory connectors, legacy filesystems drivers,
# comprehensive admin interface, and much more.

---
version: "2.1"
services:
  pydio:
    image: ghcr.io/linuxserver/pydio
    container_name: pydio
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=Europe/Amsterdam
    volumes:
      # Where pydio should store it's configuration files.
      - ${BASEDIR:-/volume1/docker}/pydio/config:/config
      # Where pydio should store uploaded files.
      - ${BASEDIR:-/volume1/docker}/pydio/data:/data
    ports:
      # WebUI
      - 443:443
    restart: unless-stopped
