# Ngircd is a free, portable and lightweight Internet Relay Chat server for
# small or private networks, developed under the GNU General Public License
# (GPL). It is easy to configure, can cope with dynamic IP addresses, and
# supports IPv6, SSL-protected connections as well as PAM for authentication. It
# is written from scratch and not based on the original IRCd.

---
version: "2.1"
services:
  ngircd:
    image: ghcr.io/linuxserver/ngircd
    container_name: ngircd
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=Europe/Amsterdam
    volumes:
      # Where `ngircd.conf` is stored
      - ${BASEDIR:-/volume1/docker}/ngircd/config:/config
    ports:
      # ngircd port
      - 6667:6667
    restart: unless-stopped
