# Apprise-api Takes advantage of [Apprise](https://github.com/caronc/apprise)
# through your network with a user-friendly API.  * Send notifications to more
# then 65+ services. * An incredibly lightweight gateway to Apprise. * A
# production ready micro-service at your disposal.  Apprise API was designed to
# easily fit into existing (and new) eco-systems that are looking for a simple
# notification solution.

---
version: "2.1"
services:
  apprise-api:
    image: ghcr.io/linuxserver/apprise-api
    container_name: apprise-api
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Where config is stored.
      - ${BASEDIR:-/volume1/docker}/apprise-api/config:/config
    ports:
      # Port for apprise's interface and API.
      - 8000:8000
    restart: unless-stopped
