# [pyLoad](https://pyload.net/) is a Free and Open Source download manager
# written in Python and designed to be extremely lightweight, easily extensible
# and fully manageable via web.

---
version: "2.1"
services:
  pyload-ng:
    image: ghcr.io/linuxserver/pyload-ng
    container_name: pyload-ng
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # pyLoad Configuration and files database
      - ${BASEDIR:-/volume1/docker}/pyload-ng/config:/config
      # Destination of pyLoad downloads
      - ${BASEDIR:-/volume1/docker}/pyload-ng/downloads:/downloads
    ports:
      # Allows HTTP access to the application
      - 8000:8000
      # Click'n'Load port.
      - 9666:9666 # optional
    restart: unless-stopped
