# [Transmission](https://www.transmissionbt.com/) is designed for easy, powerful
# use. Transmission has the features you want from a BitTorrent client:
# encryption, a web interface, peer exchange, magnet links, DHT, µTP, UPnP and
# NAT-PMP port forwarding, webseed support, watch directories, tracker editing,
# global and per-torrent speed limits, and more.

---
version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
      # Specify an alternative UI options are [`/combustion-release/`](https://github.com/Secretmapper/combustion), [`/transmission-web-control/`](https://github.com/ronggang/transmission-web-control), [`/kettu/`](https://github.com/endor/kettu) and [`/flood-for-transmission/`](https://github.com/johman10/flood-for-transmission).
      - TRANSMISSION_WEB_HOME=/combustion-release/ # optional
      # Specify an optional username for the interface
      - USER=username # optional
      # Specify an optional password for the interface
      - PASS=password # optional
      # Specify an optional list of comma separated ip whitelist. Fill rpc-whitelist setting.
      - WHITELIST=iplist # optional
      # Specify an optional list of comma separated dns name whitelist. Fill rpc-host-whitelist setting.
      - HOST_WHITELIST=dnsnane list # optional
    volumes:
      # Where transmission should store config files and logs.
      - ${BASEDIR:-/volume1/docker}/transmission/config:/config
      # Local path for downloads.
      - ${BASEDIR:-/volume1/docker}/transmission/downloads:/downloads
      # Watch folder for torrent files.
      - ${BASEDIR:-/volume1/docker}/transmission/watch:/watch
    ports:
      # WebUI
      - 9091:9091
      # Torrent Port TCP
      - 51413:51413
      # Torrent Port UDP
      - 51413:51413/udp
    restart: unless-stopped
