# Calibre is a powerful and easy to use e-book manager. Users say it’s
# outstanding and a must-have. It’ll allow you to do nearly everything and it
# takes things a step beyond normal e-book software. It’s also completely free
# and open source and great for both casual users and computer experts.

---
version: "2.1"
services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=Europe/Amsterdam
      # Username for the calibre desktop gui.
      - GUAC_USER=abc # optional
      # Password's md5 hash for the calibre desktop gui.
      - GUAC_PASS=900150983cd24fb0d6963f7d28e17f72 # optional
      # for umask setting of Calibre, default if left unset is 022.
      - UMASK_SET=022 # optional
      # Optionally pass cli start arguments to calibre.
      - CLI_ARGS= # optional
    volumes:
      # Where calibre should store its database and library.
      - ${BASEDIR:-/volume1/docker}/calibre/config:/config
    ports:
      # Calibre desktop gui.
      - 8080:8080
      # Calibre webserver gui.
      - 8081:8081
    restart: unless-stopped
