# [Calibre](https://calibre-ebook.com/) is a powerful and easy to use e-book
# manager. Users say it’s outstanding and a must-have. It’ll allow you to do
# nearly everything and it takes things a step beyond normal e-book software.
# It’s also completely free and open source and great for both casual users and
# computer experts.

---
version: "2.1"
services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
      # Optionally set a password for the gui.
      - PASSWORD= # optional
      # Optionally pass cli start arguments to calibre.
      - CLI_ARGS= # optional
    volumes:
      # Where calibre should store its database and library.
      - ${BASEDIR:-/volume1/docker}/calibre/config:/config
    ports:
      # Calibre desktop gui.
      - 8080:8080
      # Calibre webserver gui.
      - 8081:8081
    restart: unless-stopped
