This container needs special attention. Please check https://hub.docker.com/r/linuxserver/docker-compose for details.
---
version: "2.1"
services:
  docker-compose:
    image: ghcr.io/linuxserver/docker-compose
    container_name: docker-compose
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=Etc/UTC
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Configuration files.
      - ${BASEDIR:-/volume1/docker}/docker-compose/config:/config
    ports:
      # Application WebUI
      - 80:80
    restart: unless-stopped
