# [Synclounge](https://github.com/samcm/synclounge) is a third party tool that
# allows you to watch Plex in sync with your friends/family, wherever you are.

---
version: "2.1"
services:
  synclounge:
    image: ghcr.io/linuxserver/synclounge
    container_name: synclounge
    environment:
      # If set, only the users defined here and the users of the plex servers defined here will be able to access the server. Use e-mails, plex usernames and/or plex server machine ids, comma separated, no spaces.
      - AUTH_LIST=plexuser1,plexuser2,email1,machineid1 # optional
      # DEPRECATED - (Still works but will be removed in the future in favor of the built-in var `autojoin__room`) - Set to `true` to let users autojoin the server and a room (specified by the `AUTOJOIN_ROOM` var).
      - AUTOJOIN_ENABLED=false # optional
      # DEPRECATED - (Still works but will be removed in the future in favor of the built-in var `autojoin__room`) - Set the room name for auto joining (requires `AUTOJOIN_ENABLED` set to `true`).
      - AUTOJOIN_ROOM=roomname # optional
    ports:
      # Web app and server port
      - 8088:8088
    restart: unless-stopped
