# Clarkson is a web-based dashboard application that gives you a neat and clean
# interface for logging your fuel fill-ups for all of your vehicles. The
# application has full multi-user support, as well as multiple vehicles per
# user. Whenever you fill-up your car or motorcycle, keep the receipt and record
# the data in Clarkson.

---
version: "2.1"
services:
  clarkson:
    image: ghcr.io/linuxserver/clarkson
    container_name: clarkson
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Points the backend to the MySQL database. This can be either a docker hostname or an IP.
      - MYSQL_HOST=<mysql_host>
      # The user with access to the _clarkson_ schema.
      - MYSQL_USERNAME=<mysql_username>
      # The password for the user.
      - MYSQL_PASSWORD=<mysql_password>
      # **Defaults to _false_.** If set to _true_, allows new users to register.
      - ENABLE_REGISTRATIONS=<true/false>
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=Europe/Amsterdam
    ports:
      # WebUI
      - 3000:3000
    restart: unless-stopped
