# [Grav](https://github.com/getgrav/grav/) is a Fast, Simple, and Flexible,
# file-based Web-platform.

---
version: "2.1"
services:
  grav:
    image: ghcr.io/linuxserver/grav
    container_name: grav
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Contains all relevant configuration files.
      - ${BASEDIR:-/volume1/docker}/grav/config:/config
    ports:
      # Port for web frontend
      - 80:80
    restart: unless-stopped
