# Nzbget is a usenet downloader, written in C++ and designed with performance in
# mind to achieve maximum download speed by using very little system resources.

---
version: "2.1"
services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=Europe/Amsterdam
      # Supported values are LATEST, PLEXPASS or a specific version number.
      - VERSION=latest # optional
    volumes:
      # NZBGet App data.
      - ${BASEDIR:-/volume1/docker}/nzbget/config:/config
      # Location of downloads on disk.
      - ${BASEDIR:-/volume1/docker}/nzbget/downloads:/downloads
    ports:
      # WebUI
      - 6789:6789
    restart: unless-stopped
