# [Double Commander]({{ project_url }}) is a free cross platform open source
# file manager with two panels side by side. It is inspired by Total Commander
# and features some new ideas.

---
version: "2.1"
services:
  doublecommander:
    image: ghcr.io/linuxserver/doublecommander
    container_name: doublecommander
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=Europe/Amsterdam
    volumes:
      # Users home directory in the container, stores program settings.
      - ${BASEDIR:-/volume1/docker}/doublecommander/config:/config
      # Host data directories, mount as many as needed.
      - ${BASEDIR:-/volume1/docker}/doublecommander/data:/data
    ports:
      # Double Commander desktop gui.
      - 3000:3000
    restart: unless-stopped
