# [Bazarr](https://www.bazarr.media/) is a companion application to Sonarr and
# Radarr. It can manage and download subtitles based on your requirements. You
# define your preferences by TV show or movie and Bazarr takes care of
# everything for you.

---
version: "2.1"
services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Bazarr data
      - ${BASEDIR:-/volume1/docker}/bazarr/config:/config
      # Location of your movies
      - ${BASEDIR:-/volume1/docker}/bazarr/movies:/movies # optional
      # Location of your TV Shows
      - ${BASEDIR:-/volume1/docker}/bazarr/tv:/tv # optional
    ports:
      # Allows HTTP access to the internal webserver.
      - 6767:6767
    restart: unless-stopped
