This container needs special attention. Please check https://hub.docker.com/r/linuxserver/ffmpeg for details.
---
version: "2.1"
services:
  ffmpeg:
    image: ghcr.io/linuxserver/ffmpeg
    container_name: ffmpeg
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Configuration files.
      - ${BASEDIR:-/volume1/docker}/ffmpeg/config:/config
    ports:
      # Application WebUI
      - 80:80
    restart: unless-stopped
