# Requestrr is a chatbot used to simplify using services like Sonarr/Radarr/Ombi
# via the use of chat.

---
version: "2.1"
services:
  requestrr:
    image: ghcr.io/linuxserver/requestrr
    container_name: requestrr
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=Europe/Amsterdam
    volumes:
      # Contains all relevant configuration files.
      - ${BASEDIR:-/volume1/docker}/requestrr/config:/config
    ports:
      # web gui
      - 4545:4545
    restart: unless-stopped
