# [Requestrr](https://github.com/darkalfx/requestrr) is a chatbot used to
# simplify using services like Sonarr/Radarr/Ombi via the use of chat.

---
version: "2.1"
services:
  requestrr:
    image: ghcr.io/linuxserver/requestrr
    container_name: requestrr
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Contains all relevant configuration files.
      - ${BASEDIR:-/volume1/docker}/requestrr/config:/config
    ports:
      # web gui
      - 4545:4545
    restart: unless-stopped
