# The [Unifi-controller](https://www.ubnt.com/enterprise/#unifi) software is a
# powerful, enterprise wireless software engine ideal for high-density client
# deployments requiring low latency and high uptime performance.

---
version: "2.1"
services:
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=Etc/UTC
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
      # Optionally change the Java memory limit (in Megabytes). Set to `default` to reset to default
      - MEM_LIMIT=1024 # optional
      # Optionally change the Java initial/minimum memory (in Megabytes). Set to `default` to reset to default
      - MEM_STARTUP=1024 # optional
    volumes:
      # All Unifi data stored here
      - ${BASEDIR:-/volume1/docker}/unifi-controller/config:/config
    ports:
      # Unifi web admin port
      - 8443:8443
      # Unifi STUN port
      - 3478:3478/udp
      # Required for AP discovery
      - 10001:10001/udp
      # Required for device communication
      - 8080:8080
      # Required for `Make controller discoverable on L2 network` option
      - 1900:1900/udp # optional
      # Unifi guest portal HTTPS redirect port
      - 8843:8843 # optional
      # Unifi guest portal HTTP redirect port
      - 8880:8880 # optional
      # For mobile throughput test
      - 6789:6789 # optional
      # Remote syslog port
      - 5514:5514/udp # optional
    restart: unless-stopped
