# [FIleZilla](https://filezilla-project.org/) Client is a fast and reliable
# cross-platform FTP, FTPS and SFTP client with lots of useful features and an
# intuitive graphical user interface.

---
version: "2.1"
services:
  filezilla:
    image: ghcr.io/linuxserver/filezilla
    container_name: filezilla
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Users home directory in the container, stores local files and settings
      - ${BASEDIR:-/volume1/docker}/filezilla/config:/config
    ports:
      # FileZilla desktop gui.
      - 3000:3000
    restart: unless-stopped
