# [Deluge](http://deluge-torrent.org/) is a lightweight, Free Software, cross-
# platform BitTorrent client. * Full Encryption * WebUI * Plugin System * Much
# more...

---
version: "2.1"
services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
      # set the loglevel output when running Deluge, default is info for deluged and warning for delgued-web
      - DELUGE_LOGLEVEL=error # optional
    volumes:
      # deluge configs
      - ${BASEDIR:-/volume1/docker}/deluge/config:/config
      # torrent download directory
      - ${BASEDIR:-/volume1/docker}/deluge/downloads:/downloads
    ports:
      # Port for webui
      - 8112:8112
      # Inbound torrent traffic (See App Setup)
      - 6881:6881
      # Inbound torrent traffic (See App Setup)
      - 6881:6881/udp
    restart: unless-stopped
