# [digiKam](https://www.digikam.org/): Professional Photo Management with the
# Power of Open Source

---
version: "2.1"
services:
  digikam:
    image: ghcr.io/linuxserver/digikam
    container_name: digikam
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
      # Specify a subfolder to use with reverse proxies, IE `/subfolder/`
      - SUBFOLDER=/ # optional
      # See the keyboard layouts section for more information and options.
      - KEYBOARD=en-us-qwerty # optional
    volumes:
      # Users home directory in the container, stores database.
      - ${BASEDIR:-/volume1/docker}/digikam/config:/config
    ports:
      # digiKam desktop gui
      - 3000:3000 # optional
    restart: unless-stopped
