# THIS IMAGE IS DEPRECATED. We will no longer be making updates or rebuilding
# this image. The Dockerhub endpoint will stay online with the current tags for
# this software. We recommend current users switch to linuxserver/jackett.
# Cardigann a server for adding extra indexers to Sonarr, SickRage and
# CouchPotato via Torznab and TorrentPotato proxies. Behind the scenes Cardigann
# logs in and runs searches and then transforms the results into a compatible
# format.

---
version: "2.1"
services:
  cardigann:
    image: ghcr.io/linuxserver/cardigann
    container_name: cardigann
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # for using a socks proxy (optional)
      - SOCKS_PROXY=IP:PORT
      # for using a HTTP proxy (optional)
      - HTTP_PROXY=IP:PORT
    volumes:
      # Cardigann config
      - ${BASEDIR:-/volume1/docker}/cardigann/config:/config
    ports:
      # The port for the Cardigann webinterface
      - 5060:5060
    restart: unless-stopped
