# [Embystat](https://github.com/mregni/EmbyStat) is a personal web server that
# can calculate all kinds of statistics from your (local) Emby server. Just
# install this on your server and let him calculate all kinds of fun stuff.

---
version: "2.1"
services:
  embystat:
    image: ghcr.io/linuxserver/embystat
    container_name: embystat
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Contains all relevant configuration files.
      - ${BASEDIR:-/volume1/docker}/embystat/config:/config
    ports:
      # web gui
      - 6555:6555
    restart: unless-stopped
