# [Snipe-it](https://github.com/snipe/snipe-it) makes asset management easy. It
# was built by people solving real-world IT and asset management problems, and a
# solid UX has always been a top priority. Straightforward design and bulk
# actions mean getting things done faster.

---
version: "2.1"
services:
  snipe-it:
    image: ghcr.io/linuxserver/snipe-it
    container_name: snipe-it
    environment:
      # for UserID
      - PUID=${PUID:-1024}
      # for GroupID
      - PGID=${PGID:-100}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=Etc/UTC
      # Hostname or IP and port if applicable, be sure to define https/http
      - APP_URL=http://localhost:8080
      # Mysql hostname or IP to use
      - MYSQL_PORT_3306_TCP_ADDR=
      # Mysql port to use
      - MYSQL_PORT_3306_TCP_PORT=
      # Mysql database to use
      - MYSQL_DATABASE=
      # Mysql user to use
      - MYSQL_USER=
      # Mysql password to use
      - MYSQL_PASSWORD=
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
    volumes:
      # Contains your config files and data storage for Snipe-IT
      - ${BASEDIR:-/volume1/docker}/snipe-it/config:/config
    ports:
      # Snipe-IT Web UI
      - 8080:80
    restart: unless-stopped
