# [Calibre-web](https://github.com/janeczku/calibre-web) is a web app providing
# a clean interface for browsing, reading and downloading eBooks using an
# existing Calibre database. It is also possible to integrate google drive and
# edit metadata and your calibre library through the app itself. This software
# is a fork of library and licensed under the GPL v3 License.

---
version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      # for GroupID
      - PUID=${PUID:-1024}
      # for UserID
      - PGID=${PGID:-100}
      # Specify a timezone to use for example Europe/Amsterdam
      - TZ=${TZ:-Europe/Amsterdam}
      # #optional & **x86-64 only** Adds the ability to perform ebook conversion
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      # Where calibre-web stores the internal database and config.
      - ${BASEDIR:-/volume1/docker}/calibre-web/config:/config
      # Where your preexisting calibre database is locate.
      - ${BASEDIR:-/volume1/docker}/calibre-web/books:/books
    ports:
      # WebUI
      - 8083:8083
    restart: unless-stopped
